server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    host: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
ly:
  jwt:
    pubKeyPath: D:\key\id_rsa.pub
    priKeyPath: D:\key\id_rsa
    user:
      expire: 30  #过期时间30分钟
      cookieName: LY_TOKEN
      cookieDomian: leyou.com  #cookie域名
      minRefreshInterval: 15 #cookie最小刷新间隔15分钟
    app:
      expire: 1500   #过期时间1500分钟
      id: 10
      secret: ${spring.application.name}
      headerName: Privilege_token

  encoder:
    crypt:
      secret: ${random.uuid}  #随机的密钥，使用uuid
      strength: 10            #加密强度4-31，决定了密码和盐加密时的运算次数，超过10次后加密耗时会显著增加


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   #驼峰映射
  mapper-locations: classpath:com/leyou/auth/mapper/*Mapper.xml


mapper:
  wrap-keyword: "`{0}`"

logging:
  level:
    com.leyou.auth: debug


