server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/leyou
  rabbitmq:
    host: 192.168.43.67
    username: /leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true  #开启失败重试
        initial-interval: 10000ms  #第一次重试的间隔时长
        max-interval: 80000ms  #最长重试间隔，超过这个间隔将不再重试
        multiplier: 2          #下次重试间隔的倍数，此处是2即下次重试间隔是上次的2倍
      exchange: ly.sms.exchange #缺省的交换机名称，此处配置后，发送消息如果不指定交换机就会使用这个
    publisher-confirms: true   #生产者确认机制，确保消息会正确发送，如果发送失败会有错误回执，从而触发重试
  redis:
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mapper:
  wrap-keyword: "`{0}`"  #通用mapper的统一配置，全局修改关键词冲突问题

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.leyou.user: debug

ly:
  encoder:
    crypt:
      secret: ${random.uuid}   #随机的密钥，使用uuid
      strength: 10   #加密强度4-31，决定了密码和盐加密时的运算次数，超过10次后加密耗时会显著增加
