server:
  port: 8082

spring:
  application:
    name: upload-service
#限制文件上传大小
  servlet:
    multipart:
      max-file-size: 5MB

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

logging:
  level:
    com.leyou: debug

ly:
  oss:
    accessKeyId:
    accessKeySecret: 
    bucket: 
    endpoint: 
    host: 
    dir: ""  # 保存到bucket的某个子目录
    expireTime: 20      #过期时间，20秒
    maxFileSize: 5242880  #文件上传大小
