server:
  port: 8083
spring:
  application:
    name: ly-search
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.43.67:9300
  rabbitmq:
    host: 192.168.43.67
    username: /leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #每5秒从注册中心拉取服务
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true

logging:
  level:
    com.leyou.search: debug
